CREATE TABLE user (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE game (
	id INT PRIMARY_KEY AUTO_INCREMENT,
	external_url VARCHAR(500) NULL
	source VARCHAR(255) NOT NULL
	name VARCHAR(255) NOT NULL
	release_date DATETIME NULL
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
		
	UNIQUE KEY unique_external (source, external_url)
);

CREATE TABLE wishlist (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	game_id INT NOT NULL,
	added_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	notified_at DATETIME NULL,
	
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
	FOREIGN KEY (game_id) REFERENCES game(id) ON DELETE CASCADE,
	
	UNIQUE KEY (user_id, game_id)
)